#############################################################################
# Makefile for building: Regit
# Generated by qmake (1.07a) (Qt 3.3.7) on: Sat Dec  8 01:30:54 2007
# Project:  Regit.pro
# Template: app
# Command: $(QMAKE) -o Makefile Regit.pro
#############################################################################

####### Compiler, tools and options

CC       = gcc
CXX      = g++
LEX      = flex
YACC     = yacc
CFLAGS   = -pipe -Wall -W -O2 -D_REENTRANT  -DQT_NO_DEBUG -DQT_THREAD_SUPPORT -DQT_SHARED -DQT_TABLET_SUPPORT
CXXFLAGS = -pipe -Wall -W -O2 -D_REENTRANT  -DQT_NO_DEBUG -DQT_THREAD_SUPPORT -DQT_SHARED -DQT_TABLET_SUPPORT
LEXFLAGS = 
YACCFLAGS= -d
INCPATH  = -I/usr/share/qt3/mkspecs/default -I. -I. -Isrc -Ixml -I/usr/include/qt3
LINK     = g++
LFLAGS   = 
LIBS     = $(SUBLIBS) -L/usr/share/qt3/lib -L/usr/X11R6/lib -lqt-mt -lXext -lX11 -lm -lpthread
AR       = ar cqs
RANLIB   = 
MOC      = /usr/share/qt3/bin/moc
UIC      = /usr/share/qt3/bin/uic
QMAKE    = qmake
TAR      = tar -cf
GZIP     = gzip -9f
COPY     = cp -f
COPY_FILE= $(COPY)
COPY_DIR = $(COPY) -r
INSTALL_FILE= $(COPY_FILE)
INSTALL_DIR = $(COPY_DIR)
DEL_FILE = rm -f
SYMLINK  = ln -sf
DEL_DIR  = rmdir
MOVE     = mv -f
CHK_DIR_EXISTS= test -d
MKDIR    = mkdir -p

####### Output directory

OBJECTS_DIR = ./

####### Files

HEADERS = Regit.ui.h \
		Creator/creator.ui.h \
		src/behaviour.h \
		src/classcreator.h \
		src/codes.h \
		src/date.h \
		src/dater.h \
		src/student.h \
		src/timetable.h \
		src/value.h \
		StudentDayStat/StudentDayStat.ui.h \
		xml/common.h \
		xml/xmltraversal.h
SOURCES = main.cpp \
		src/behaviour.cpp \
		src/classcreator.cpp \
		src/date.cpp \
		src/dater.cpp \
		src/student.cpp \
		src/timetable.cpp \
		src/value.cpp \
		xml/src/xmltraversal.cpp
OBJECTS = main.o \
		behaviour.o \
		classcreator.o \
		date.o \
		dater.o \
		student.o \
		timetable.o \
		value.o \
		xmltraversal.o \
		Regit.o \
		creator.o \
		StudentDayStat.o \
		qmake_image_collection.o
FORMS = Regit.ui \
		Creator/creator.ui \
		StudentDayStat/StudentDayStat.ui
UICDECLS = Regit.h \
		Creator/creator.h \
		StudentDayStat/StudentDayStat.h
UICIMPLS = Regit.cpp \
		Creator/creator.cpp \
		StudentDayStat/StudentDayStat.cpp
SRCMOC   = moc_Regit.cpp \
		Creator/moc_creator.cpp \
		StudentDayStat/moc_StudentDayStat.cpp
OBJMOC = moc_Regit.o \
		moc_creator.o \
		moc_StudentDayStat.o
DIST	   = Regit.pro
QMAKE_TARGET = Regit
DESTDIR  = 
TARGET   = Regit

first: all
####### Implicit rules

.SUFFIXES: .c .o .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o $@ $<

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(UICDECLS) $(OBJECTS) $(OBJMOC)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJMOC) $(OBJCOMP) $(LIBS)

mocables: $(SRCMOC)
uicables: $(UICDECLS) $(UICIMPLS)

$(MOC): 
	( cd $(QTDIR)/src/moc && $(MAKE) )

Makefile: Regit.pro  /usr/share/qt3/mkspecs/default/qmake.conf /usr/share/qt3/lib/libqt-mt.prl
	$(QMAKE) -o Makefile Regit.pro
qmake: 
	@$(QMAKE) -o Makefile Regit.pro

dist: 
	@mkdir -p .tmp/Regit && $(COPY_FILE) --parents $(SOURCES) $(HEADERS) $(FORMS) $(DIST) .tmp/Regit/ && $(COPY_FILE) --parents images/absent.xpm images/absentwb.xpm images/behaviour.xpm images/delete_table_col.png images/editcopy images/editcut images/editpaste images/FieldTrip.xpm images/FieldTripwb.xpm images/fileclose.png images/filenew images/fileopen images/filesave images/late.xpm images/latewb.xpm images/new.png images/newstudent.xpm images/popuser.xpm images/present.xpm images/presentwb.xpm images/preview.png images/print images/redo images/searchfind images/tool_delete.png images/undo images/validators.png .tmp/Regit/ && $(COPY_FILE) --parents Regit.ui.h Creator/creator.ui.h StudentDayStat/StudentDayStat.ui.h .tmp/Regit/ && ( cd `dirname .tmp/Regit` && $(TAR) Regit.tar Regit && $(GZIP) Regit.tar ) && $(MOVE) `dirname .tmp/Regit`/Regit.tar.gz . && $(DEL_FILE) -r .tmp/Regit

mocclean:
	-$(DEL_FILE) $(OBJMOC)
	-$(DEL_FILE) $(SRCMOC)

uiclean:
	-$(DEL_FILE) $(UICIMPLS) $(UICDECLS)

yaccclean:
lexclean:
clean: mocclean uiclean
	-$(DEL_FILE) $(OBJECTS)
		-$(DEL_FILE) qmake_image_collection.cpp
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) $(TARGET)


FORCE:

####### Compile

main.o: main.cpp Regit.h \
		src/timetable.h \
		src/student.h \
		src/dater.h \
		src/behaviour.h \
		src/value.h \
		src/codes.h \
		src/date.h

behaviour.o: src/behaviour.cpp src/behaviour.h \
		src/codes.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o behaviour.o src/behaviour.cpp

classcreator.o: src/classcreator.cpp src/timetable.h \
		src/dater.h \
		src/codes.h \
		src/classcreator.h \
		src/student.h \
		src/behaviour.h \
		src/value.h \
		src/date.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o classcreator.o src/classcreator.cpp

date.o: src/date.cpp src/date.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o date.o src/date.cpp

dater.o: src/dater.cpp src/dater.h \
		src/codes.h \
		src/date.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dater.o src/dater.cpp

student.o: src/student.cpp src/student.h \
		src/behaviour.h \
		src/value.h \
		src/codes.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o student.o src/student.cpp

timetable.o: src/timetable.cpp src/timetable.h \
		src/codes.h \
		src/student.h \
		src/dater.h \
		src/behaviour.h \
		src/value.h \
		src/date.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o timetable.o src/timetable.cpp

value.o: src/value.cpp src/value.h \
		src/codes.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o value.o src/value.cpp

xmltraversal.o: xml/src/xmltraversal.cpp xml/xmltraversal.h \
		xml/common.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o xmltraversal.o xml/src/xmltraversal.cpp

Regit.h: Regit.ui src/timetable.h \
		src/student.h \
		src/dater.h \
		src/behaviour.h \
		src/value.h \
		src/codes.h \
		src/date.h
	$(UIC) Regit.ui -o Regit.h

Regit.cpp: Regit.h Regit.ui Regit.ui.h src/timetable.h \
		src/student.h \
		src/dater.h \
		src/behaviour.h \
		src/value.h \
		src/codes.h \
		src/date.h
	$(UIC) Regit.ui -i Regit.h -o Regit.cpp

Creator/creator.h: Creator/creator.ui src/timetable.h \
		src/classcreator.h \
		src/codes.h \
		src/student.h \
		src/dater.h \
		src/behaviour.h \
		src/value.h \
		src/date.h
	$(UIC) Creator/creator.ui -o Creator/creator.h

Creator/creator.cpp: Creator/creator.h Creator/creator.ui Creator/creator.ui.h src/timetable.h \
		src/classcreator.h \
		src/codes.h \
		src/student.h \
		src/dater.h \
		src/behaviour.h \
		src/value.h \
		src/date.h
	$(UIC) Creator/creator.ui -i creator.h -o Creator/creator.cpp

StudentDayStat/StudentDayStat.h: StudentDayStat/StudentDayStat.ui src/timetable.h \
		src/student.h \
		src/dater.h \
		src/behaviour.h \
		src/value.h \
		src/codes.h \
		src/date.h
	$(UIC) StudentDayStat/StudentDayStat.ui -o StudentDayStat/StudentDayStat.h

StudentDayStat/StudentDayStat.cpp: StudentDayStat/StudentDayStat.h StudentDayStat/StudentDayStat.ui StudentDayStat/StudentDayStat.ui.h src/timetable.h \
		src/student.h \
		src/dater.h \
		src/behaviour.h \
		src/value.h \
		src/codes.h \
		src/date.h
	$(UIC) StudentDayStat/StudentDayStat.ui -i StudentDayStat.h -o StudentDayStat/StudentDayStat.cpp

Regit.o: Regit.cpp src/codes.h \
		src/date.h \
		src/timetable.h \
		src/classcreator.h \
		Creator/creator.h \
		StudentDayStat/StudentDayStat.h \
		Regit.ui.h \
		Regit.h

creator.o: Creator/creator.cpp Creator/creator.ui.h \
		Creator/creator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o creator.o Creator/creator.cpp

StudentDayStat.o: StudentDayStat/StudentDayStat.cpp StudentDayStat/StudentDayStat.ui.h \
		StudentDayStat/StudentDayStat.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o StudentDayStat.o StudentDayStat/StudentDayStat.cpp

moc_Regit.o: moc_Regit.cpp  Regit.h src/timetable.h \
		src/student.h \
		src/dater.h \
		src/behaviour.h \
		src/value.h \
		src/codes.h \
		src/date.h

moc_creator.o: Creator/moc_creator.cpp  Creator/creator.h 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_creator.o Creator/moc_creator.cpp

moc_StudentDayStat.o: StudentDayStat/moc_StudentDayStat.cpp  StudentDayStat/StudentDayStat.h 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_StudentDayStat.o StudentDayStat/moc_StudentDayStat.cpp

moc_Regit.cpp: $(MOC) Regit.h
	$(MOC) Regit.h -o moc_Regit.cpp

Creator/moc_creator.cpp: $(MOC) Creator/creator.h
	$(MOC) Creator/creator.h -o Creator/moc_creator.cpp

StudentDayStat/moc_StudentDayStat.cpp: $(MOC) StudentDayStat/StudentDayStat.h
	$(MOC) StudentDayStat/StudentDayStat.h -o StudentDayStat/moc_StudentDayStat.cpp

qmake_image_collection.o: qmake_image_collection.cpp

qmake_image_collection.cpp: images/absent.xpm \
		images/absentwb.xpm \
		images/behaviour.xpm \
		images/delete_table_col.png \
		images/editcopy \
		images/editcut \
		images/editpaste \
		images/FieldTrip.xpm \
		images/FieldTripwb.xpm \
		images/fileclose.png \
		images/filenew \
		images/fileopen \
		images/filesave \
		images/late.xpm \
		images/latewb.xpm \
		images/new.png \
		images/newstudent.xpm \
		images/popuser.xpm \
		images/present.xpm \
		images/presentwb.xpm \
		images/preview.png \
		images/print \
		images/redo \
		images/searchfind \
		images/tool_delete.png \
		images/undo \
		images/validators.png
	$(UIC)  -embed Regit images/absent.xpm images/absentwb.xpm images/behaviour.xpm images/delete_table_col.png images/editcopy images/editcut images/editpaste images/FieldTrip.xpm images/FieldTripwb.xpm images/fileclose.png images/filenew images/fileopen images/filesave images/late.xpm images/latewb.xpm images/new.png images/newstudent.xpm images/popuser.xpm images/present.xpm images/presentwb.xpm images/preview.png images/print images/redo images/searchfind images/tool_delete.png images/undo images/validators.png -o qmake_image_collection.cpp

####### Install

install:  

uninstall:  

